tools:
  - name: core/createUserMessage
    service: createDocument
    props:
      document: core/userMessage
      update:
        content:
          role: user
          content: ${ workflow.options.message }