tools:
  - name: core/createErrorMessage
    service: createDocument
    props:
      document: core/assistantMessage
      update:
        content:
          role: assistant
          content: ${ workflow.options.message }
