tools:
  - name: core/createAssistantMessage
    service: CreateDocumentService
    props:
      document: core/assistantMessage
      update:
        content:
          role: assistant
          content: ${ workflow.options.message }
