name: 'Push Main Workflow'

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-test-workflow:
    name: 'Run CI'
    uses: ./.github/workflows/ci-test.yml
    with:
      node-version: '20'
