documents:
  - name: Common/InternalMessage
    tags:
      - message
      - internal
    ui:
      widget: chat-message
    schema:
      type: object
    meta:
      invalidate: false
    content:
      role: user
      content: ""