documents:
  - name: Core/UserMessage
    tags:
      - message
    ui:
      widget: chat-message
    schema:
      type: object
    meta:
      invalidate: false
    content:
      role: user
      content: ""