tools:
  - name: create_document
    parameters:
      type: object
      properties:
        document:
          type: string
        validate:
          type: string
          enum:
            - strict
            - safe
            - skip
        content:
          type: any
        schema:
          type: any
        ui:
          type: any
      required:
        - document
      additionalProperties: false
    execute:
      - handler: CreateDocumentHandler
        arguments:
          document: ${ arguments.document }
          validate: ${ arguments.validate }
          update:
            content: ${ arguments.content }
            ui: ${ arguments.ui }
            schema: ${ arguments.schema }