tools:
  - name: set_context
    parameters:
      type: object
      properties:
        key:
          type: string
        value:
          type: any
    execute:
      handler: SetContextHandler
      arguments:
        key: ${ arguments.key }
        value: ${ arguments.value }