tools:
  - name: sql_query
    parameters:
      type: object
      properties:
        entity:
          type: string
        query:
          type: string
        parameters:
          type: array
          items:
            type:
              - string
              - number
              - boolean
      required:
        - entity
        - query
      additionalProperties: false
    execute:
      handler: SqlQueryHandler
      arguments:
        entity: ${ arguments.entity }
        query: ${ arguments.query }
        parameters: ${ arguments.parameters }