tools:
  - name: validate
    parameters:
      type: object
      properties:
        source:
          type: any
        schema:
          type: any
        message:
          type: string
      required:
        - source
        - schema
      additionalProperties: false
    execute:
      - handler: ValidateHandler
        arguments:
          source: ${ arguments.source }
          schema: ${ arguments.schema }
          message: ${ arguments.message }