tools:
  - name: validate_document
    parameters:
      type: object
      properties:
        documentId:
          type: string
        message:
          type: string
      required:
        - documentId
      additionalProperties: false
    execute:
      - handler: ValidateDocumentHandler
        arguments:
          documentId: ${ arguments.documentId }
          message: ${ arguments.message }