documents:
  - name: message
    tags:
      - message
    ui:
      widget: chat-message
    schema:
      type: object
      properties: 
        role:
          type: string
        content:
          type: any
#      additionalProperties: false
    meta:
      invalidate: false
      level: info
